In [13]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
import joblib
from sklearn.cluster import KMeans
from kmodes.kmodes import KModes

In [14]:
df = pd.read_csv('census_ml.csv')
df.head(1)

,year,sample,serial,hhwt,cluster,perwt,nchild,nchild_under_5,nsibs,eldch,sex,age,birthyr,race,educ,ed_var_detailed,occ,occ1950,ed_group_h
0,1960,1960 5%,69847,20,1.960000e+12,20,0 children present,No children under age 5,0 siblings,NaN,Male,43,1916,White,"Grade 5, 6, 7, or 8",Grade 8,775,Operative and kindred workers (nec),1

In [15]:
df = df.drop(labels=['year','sample','serial','hhwt','cluster','perwt','nchild','nchild_under_5', 'nsibs', 'eldch', 'sex',
                    'age','birthyr','race', 'educ', 'ed_var_detailed','occ'], axis=1)
df.head(5)

                                      occ1950  ed_group_h
0         Operative and kindred workers (nec)           1
1  Managers, officials, and proprietors (nec)           2
2                               Foremen (nec)           1
3  Managers, officials, and proprietors (nec)           1
4             Salesmen and sales clerks (nec)           1

In [16]:
dummies =  pd.get_dummies(df.occ1950)

In [17]:
census = pd.concat([df, dummies], axis='columns')
census

,occ1950,ed_group_h,Accountants and auditors,Actors and actresses,Advertising agents and salesmen,Aeronautical-Engineers,Agents (nec),Agricultural sciences-Professors and instructors,Agricultural scientists,Airplane pilots and navigators,...,"Tinsmiths, coppersmiths, and sheet metal workers","Tool makers, and die makers and setters",Truck and tractor drivers,Upholsterers,"Ushers, recreation and amusement",Veterinarians,Waiters and waitresses,Watchmen (crossing) and bridge tenders,"Weavers, textile",Welders and flame cutters
0,Operative and kindred workers (nec),1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,"Managers, officials, and proprietors (nec)",2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Foremen (nec),1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,"Managers, officials, and proprietors (nec)",1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Salesmen and sales clerks (nec),1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203593,Clergymen,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
203594,Occupation missing/unknown,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
203595,"Buyers and dept heads, store",2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
203596,"Dispatchers and starters, vehicle",2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
203597,"Managers, officials, and proprietors (nec)",3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [18]:
census = census.drop(labels=['occ1950','Milliners' ], axis='columns')
census

,ed_group_h,Accountants and auditors,Actors and actresses,Advertising agents and salesmen,Aeronautical-Engineers,Agents (nec),Agricultural sciences-Professors and instructors,Agricultural scientists,Airplane pilots and navigators,Airplane-mechanics and repairmen,...,"Tinsmiths, coppersmiths, and sheet metal workers","Tool makers, and die makers and setters",Truck and tractor drivers,Upholsterers,"Ushers, recreation and amusement",Veterinarians,Waiters and waitresses,Watchmen (crossing) and bridge tenders,"Weavers, textile",Welders and flame cutters
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203593,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
203594,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
203595,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
203596,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
203597,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [19]:
census['ed_group_h'].unique()

array([1, 2, 4, 3], dtype=int64)

In [20]:
x = census.reset_index().values

In [21]:
km = KModes(n_clusters=4,init='Huang', n_init=5, verbose=1)

In [ ]:
clusters = km.fit_predict(x)

In [ ]:
census['clusters'] = clusters

In [ ]:
from sklearn.decomposition import PCA
pca = PCA(2)
census.head(5)

In [ ]:
#Turn the modified census into two columns with PCA
plot_columns = pca.fit_transform(census.ix[])